# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import finnhub
from finnhub.models.stock_transcripts import StockTranscripts  # noqa: E501
from finnhub.rest import ApiException

class TestStockTranscripts(unittest.TestCase):
    """StockTranscripts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test StockTranscripts
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = finnhub.models.stock_transcripts.StockTranscripts()  # noqa: E501
        if include_optional :
            return StockTranscripts(
                id = '0', 
                title = '0', 
                time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                year = 56, 
                quarter = 56
            )
        else :
            return StockTranscripts(
        )

    def testStockTranscripts(self):
        """Test StockTranscripts"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
