# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import finnhub
from finnhub.models.company_profile2 import CompanyProfile2  # noqa: E501
from finnhub.rest import ApiException

class TestCompanyProfile2(unittest.TestCase):
    """CompanyProfile2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CompanyProfile2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = finnhub.models.company_profile2.CompanyProfile2()  # noqa: E501
        if include_optional :
            return CompanyProfile2(
                country = '0', 
                currency = '0', 
                exchange = '0', 
                name = '0', 
                ticker = '0', 
                ipo = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                market_capitalization = 1.337, 
                share_outstanding = 1.337, 
                logo = '0', 
                phone = '0', 
                weburl = '0', 
                finnhub_industry = '0'
            )
        else :
            return CompanyProfile2(
        )

    def testCompanyProfile2(self):
        """Test CompanyProfile2"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
