# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from finnhub.configuration import Configuration


class Indicator(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'buy': 'int',
        'neutral': 'int',
        'sell': 'int'
    }

    attribute_map = {
        'buy': 'buy',
        'neutral': 'neutral',
        'sell': 'sell'
    }

    def __init__(self, buy=None, neutral=None, sell=None, local_vars_configuration=None):  # noqa: E501
        """Indicator - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._buy = None
        self._neutral = None
        self._sell = None
        self.discriminator = None

        if buy is not None:
            self.buy = buy
        if neutral is not None:
            self.neutral = neutral
        if sell is not None:
            self.sell = sell

    @property
    def buy(self):
        """Gets the buy of this Indicator.  # noqa: E501

        Number of buy signals  # noqa: E501

        :return: The buy of this Indicator.  # noqa: E501
        :rtype: int
        """
        return self._buy

    @buy.setter
    def buy(self, buy):
        """Sets the buy of this Indicator.

        Number of buy signals  # noqa: E501

        :param buy: The buy of this Indicator.  # noqa: E501
        :type: int
        """

        self._buy = buy

    @property
    def neutral(self):
        """Gets the neutral of this Indicator.  # noqa: E501

        Number of neutral signals  # noqa: E501

        :return: The neutral of this Indicator.  # noqa: E501
        :rtype: int
        """
        return self._neutral

    @neutral.setter
    def neutral(self, neutral):
        """Sets the neutral of this Indicator.

        Number of neutral signals  # noqa: E501

        :param neutral: The neutral of this Indicator.  # noqa: E501
        :type: int
        """

        self._neutral = neutral

    @property
    def sell(self):
        """Gets the sell of this Indicator.  # noqa: E501

        Number of sell signals  # noqa: E501

        :return: The sell of this Indicator.  # noqa: E501
        :rtype: int
        """
        return self._sell

    @sell.setter
    def sell(self, sell):
        """Sets the sell of this Indicator.

        Number of sell signals  # noqa: E501

        :param sell: The sell of this Indicator.  # noqa: E501
        :type: int
        """

        self._sell = sell

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Indicator):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Indicator):
            return True

        return self.to_dict() != other.to_dict()
