# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from finnhub.configuration import Configuration


class Sentiment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'bearish_percent': 'int',
        'bullish_percent': 'int'
    }

    attribute_map = {
        'bearish_percent': 'bearishPercent',
        'bullish_percent': 'bullishPercent'
    }

    def __init__(self, bearish_percent=None, bullish_percent=None, local_vars_configuration=None):  # noqa: E501
        """Sentiment - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._bearish_percent = None
        self._bullish_percent = None
        self.discriminator = None

        if bearish_percent is not None:
            self.bearish_percent = bearish_percent
        if bullish_percent is not None:
            self.bullish_percent = bullish_percent

    @property
    def bearish_percent(self):
        """Gets the bearish_percent of this Sentiment.  # noqa: E501

          # noqa: E501

        :return: The bearish_percent of this Sentiment.  # noqa: E501
        :rtype: int
        """
        return self._bearish_percent

    @bearish_percent.setter
    def bearish_percent(self, bearish_percent):
        """Sets the bearish_percent of this Sentiment.

          # noqa: E501

        :param bearish_percent: The bearish_percent of this Sentiment.  # noqa: E501
        :type: int
        """

        self._bearish_percent = bearish_percent

    @property
    def bullish_percent(self):
        """Gets the bullish_percent of this Sentiment.  # noqa: E501

          # noqa: E501

        :return: The bullish_percent of this Sentiment.  # noqa: E501
        :rtype: int
        """
        return self._bullish_percent

    @bullish_percent.setter
    def bullish_percent(self, bullish_percent):
        """Sets the bullish_percent of this Sentiment.

          # noqa: E501

        :param bullish_percent: The bullish_percent of this Sentiment.  # noqa: E501
        :type: int
        """

        self._bullish_percent = bullish_percent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Sentiment):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Sentiment):
            return True

        return self.to_dict() != other.to_dict()
