# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from finnhub.configuration import Configuration


class TickData(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'timestamp': 'int',
        'price': 'float',
        'volume': 'float'
    }

    attribute_map = {
        'timestamp': 'timestamp',
        'price': 'price',
        'volume': 'volume'
    }

    def __init__(self, timestamp=None, price=None, volume=None, local_vars_configuration=None):  # noqa: E501
        """TickData - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._timestamp = None
        self._price = None
        self._volume = None
        self.discriminator = None

        if timestamp is not None:
            self.timestamp = timestamp
        if price is not None:
            self.price = price
        if volume is not None:
            self.volume = volume

    @property
    def timestamp(self):
        """Gets the timestamp of this TickData.  # noqa: E501

        UNIX milliseconds timestamp.  # noqa: E501

        :return: The timestamp of this TickData.  # noqa: E501
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """Sets the timestamp of this TickData.

        UNIX milliseconds timestamp.  # noqa: E501

        :param timestamp: The timestamp of this TickData.  # noqa: E501
        :type: int
        """

        self._timestamp = timestamp

    @property
    def price(self):
        """Gets the price of this TickData.  # noqa: E501

        Price.  # noqa: E501

        :return: The price of this TickData.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this TickData.

        Price.  # noqa: E501

        :param price: The price of this TickData.  # noqa: E501
        :type: float
        """

        self._price = price

    @property
    def volume(self):
        """Gets the volume of this TickData.  # noqa: E501

        Volume of the trade.  # noqa: E501

        :return: The volume of this TickData.  # noqa: E501
        :rtype: float
        """
        return self._volume

    @volume.setter
    def volume(self, volume):
        """Sets the volume of this TickData.

        Volume of the trade.  # noqa: E501

        :param volume: The volume of this TickData.  # noqa: E501
        :type: float
        """

        self._volume = volume

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TickData):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TickData):
            return True

        return self.to_dict() != other.to_dict()
