# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from finnhub.configuration import Configuration


class Trade(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        's': 'str',
        'p': 'float',
        't': 'int',
        'v': 'float'
    }

    attribute_map = {
        's': 's',
        'p': 'p',
        't': 't',
        'v': 'v'
    }

    def __init__(self, s=None, p=None, t=None, v=None, local_vars_configuration=None):  # noqa: E501
        """Trade - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._s = None
        self._p = None
        self._t = None
        self._v = None
        self.discriminator = None

        if s is not None:
            self.s = s
        if p is not None:
            self.p = p
        if t is not None:
            self.t = t
        if v is not None:
            self.v = v

    @property
    def s(self):
        """Gets the s of this Trade.  # noqa: E501

        Symbol.  # noqa: E501

        :return: The s of this Trade.  # noqa: E501
        :rtype: str
        """
        return self._s

    @s.setter
    def s(self, s):
        """Sets the s of this Trade.

        Symbol.  # noqa: E501

        :param s: The s of this Trade.  # noqa: E501
        :type: str
        """

        self._s = s

    @property
    def p(self):
        """Gets the p of this Trade.  # noqa: E501

        Last price.  # noqa: E501

        :return: The p of this Trade.  # noqa: E501
        :rtype: float
        """
        return self._p

    @p.setter
    def p(self, p):
        """Sets the p of this Trade.

        Last price.  # noqa: E501

        :param p: The p of this Trade.  # noqa: E501
        :type: float
        """

        self._p = p

    @property
    def t(self):
        """Gets the t of this Trade.  # noqa: E501

        UNIX milliseconds timestamp.  # noqa: E501

        :return: The t of this Trade.  # noqa: E501
        :rtype: int
        """
        return self._t

    @t.setter
    def t(self, t):
        """Sets the t of this Trade.

        UNIX milliseconds timestamp.  # noqa: E501

        :param t: The t of this Trade.  # noqa: E501
        :type: int
        """

        self._t = t

    @property
    def v(self):
        """Gets the v of this Trade.  # noqa: E501

        Volume.  # noqa: E501

        :return: The v of this Trade.  # noqa: E501
        :rtype: float
        """
        return self._v

    @v.setter
    def v(self, v):
        """Sets the v of this Trade.

        Volume.  # noqa: E501

        :param v: The v of this Trade.  # noqa: E501
        :type: float
        """

        self._v = v

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Trade):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Trade):
            return True

        return self.to_dict() != other.to_dict()
