# coding: utf-8

"""
    Finnhub API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from finnhub.configuration import Configuration


class TranscriptContent(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'speech': 'str'
    }

    attribute_map = {
        'name': 'name',
        'speech': 'speech'
    }

    def __init__(self, name=None, speech=None, local_vars_configuration=None):  # noqa: E501
        """TranscriptContent - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._name = None
        self._speech = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if speech is not None:
            self.speech = speech

    @property
    def name(self):
        """Gets the name of this TranscriptContent.  # noqa: E501

        Speaker's name  # noqa: E501

        :return: The name of this TranscriptContent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TranscriptContent.

        Speaker's name  # noqa: E501

        :param name: The name of this TranscriptContent.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def speech(self):
        """Gets the speech of this TranscriptContent.  # noqa: E501

        Speaker's speech  # noqa: E501

        :return: The speech of this TranscriptContent.  # noqa: E501
        :rtype: str
        """
        return self._speech

    @speech.setter
    def speech(self, speech):
        """Sets the speech of this TranscriptContent.

        Speaker's speech  # noqa: E501

        :param speech: The speech of this TranscriptContent.  # noqa: E501
        :type: str
        """

        self._speech = speech

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranscriptContent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranscriptContent):
            return True

        return self.to_dict() != other.to_dict()
